/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * tc358746 - Toshiba Parallel to CSI-2 bridge - register names and bit masks
 *
 * Convention:
 * <REGISTER>
 * <REGISTER>_<BITFIELD>_MASK
 * <REGISTER>_<BITFIELD>_<VALUE>
 * <REGISTER>_<BITFIELD>_SET(val = <REGISTER>_<BITFIELD>_<VALUE>)
 *
 * References:
 * REF_01:
 * - TC358746AXBG/TC358748XBG/TC358748IXBG Functional Specification Rev 1.2
 */

#ifndef __TC358746_REGS_H
#define __TC358746_REGS_H

#define TC358746_I2C_ADDR		0x0e

#define CHIPID			0x0000
#define CHIPID_CHIPID_MASK		GENMASK(15, 8)
#define CHIPID_REVID_MASK		GENMASK(7, 0)

#define SYSCTL			0x0002
#define SYSCTL_SLEEP_MASK		BIT(1)
#define SYSCTL_SRESET_MASK		BIT(0)

#define CONFCTL                 0x0004
#define CONFCTL_TRIEN_MASK		BIT(15)
#define CONFCTL_INTE2N_MASK		BIT(13)
#define CONFCTL_BT656EN_MASK		BIT(12)
#define CONFCTL_PDATAF_MASK		GENMASK(9, 8)
#define CONFCTL_PDATAF_SET(val)		(((val << 8) & CONFCTL_PDATAF_MASK))
#define CONFCTL_PDATAF_MODE0		0
#define CONFCTL_PDATAF_MODE1		1
#define CONFCTL_PDATAF_MODE2		2
#define CONFCTL_PPEN_MASK		BIT(6)
#define CONFCTL_VVALIDP_MASK		BIT(5)
#define CONFCTL_HVALIDP_MASK		BIT(4)
#define CONFCTL_PCLKP_MASK		BIT(3)
#define CONFCTL_AUTO_MASK		BIT(2)
#define CONFCTL_DATALANE_MASK		GENMASK(1, 0)
#define CONFCTL_DATALANE_1		0
#define CONFCTL_DATALANE_2		1
#define CONFCTL_DATALANE_3		2
#define CONFCTL_DATALANE_4		3

#define FIFOCTL			0x0006
#define DATAFMT			0x0008
#define DATAFMT_PDFMT_RAW8		0
#define DATAFMT_PDFMT_RAW10		1
#define DATAFMT_PDFMT_RAW12		2
#define DATAFMT_PDFMT_RGB888		3
#define DATAFMT_PDFMT_RGB666		4
#define DATAFMT_PDFMT_RGB565		5
#define DATAFMT_PDFMT_YCBCRFMT_422_8_BIT 6
#define DATAFMT_PDFMT_RAW14		8
#define DATAFMT_PDFMT_YCBCRFMT_422_10_BIT 9
#define DATAFMT_PDFMT_YCBCRFMT_444	10
#define DATAFMT_PDFMT_MASK		GENMASK(7, 4)
#define DATAFMT_PDFMT_SET(val)		(((val) << 4) & DATAFMT_PDFMT_MASK)
#define DATAFMT_UDT_EN_MASK		BIT(0)

#define MCLKCTL			0x000c
#define MCLKCTL_MCLK_HIGH_MASK		GENMASK(15, 8)
#define MCLKCTL_MCLK_HIGH_SET(val)	((((val) - 1) << 8) & MCLKCTL_MCLK_HIGH_MASK)
#define MCLKCTL_MCLK_LOW_MASK		GENMASK(7, 0)
#define MCLKCTL_MCLK_LOW_SET(val)	(((val) - 1) & MCLKCTL_MCLK_LOW_MASK)

#define PLLCTL0			0x0016
#define PLLCTL0_PLL_PRD_MASK		GENMASK(15, 12)
#define PLLCTL0_PLL_PRD_SET(prd)	((((prd) - 1) << 12) & PLLCTL0_PLL_PRD_MASK)
#define PLLCTL0_PLL_FBD_MASK		GENMASK(8, 0)
#define PLLCTL0_PLL_FBD_SET(fbd)        (((fbd) - 1) & PLLCTL0_PLL_FBD_MASK)

#define PLLCTL1                 0x0018
#define PLLCTL1_PLL_FRS_MASK            GENMASK(11, 10)
#define PLLCTL1_PLL_FRS_SET(frs)        (((frs) << 10) & PLLCTL1_PLL_FRS_MASK)
#define PLLCTL1_PLL_LBWS_MASK		GENMASK(9, 8)
#define PLLCTL1_LFBREN_MASK		BIT(6)
#define PLLCTL1_BYPCKEN_MASK		BIT(5)
#define PLLCTL1_CKEN_MASK		BIT(4)
#define PLLCTL1_RESETB_MASK		BIT(1)
#define PLLCTL1_PLL_EN_MASK		BIT(0)

#define CLKCTL			0x0020
#define CLKCTL_MCLKDIV_MASK		GENMASK(3, 2)
#define CLKCTL_MCLKDIV_SET(val)		((val << 2) & CLKCTL_MCLKDIV_MASK)
#define CLKCTL_MCLKDIV_8		0
#define CLKCTL_MCLKDIV_4		1
#define CLKCTL_MCLKDIV_2		2

#define WORDCNT			0x0022
#define PP_MISC                 0x0032
#define PP_MISC_FRMSTOP_MASK		BIT(15)
#define PP_MISC_RSTPTR_MASK		BIT(14)

#define CSI2TX_DATA_TYPE	0x0050
#define MIPI_PHY_STATUS		0x0062
#define CSI2_ERROR_STATUS       0x0064
#define CSI2_ERR_EN             0x0066
#define CSI2_IDID_ERROR         0x006c
#define DBG_ACT_LINE_CNT        0x00e0
#define DBG_LINE_WIDTH		0x00e2
#define DBG_VERT_BLANK_LINE_CNT	0x00e4
#define DBG_VIDEO_DATA          0x00e8
#define FIFOSTATUS              0x00F8

#define CLW_CNTRL               0x0140
#define CLW_CNTRL_CLW_LANEDISABLE_MASK	BIT(0)

#define D0W_CNTRL               0x0144
#define D0W_CNTRL_D0W_LANEDISABLE_MASK	BIT(0)

#define D1W_CNTRL		0x0148
#define D1W_CNTRL_D1W_LANEDISABLE_MASK	BIT(0)

#define D2W_CNTRL		0x014C
#define D2W_CNTRL_D2W_LANEDISABLE_MASK	BIT(0)

#define D3W_CNTRL		0x0150
#define D2W_CNTRL_D3W_LANEDISABLE_MASK	BIT(0)

#define STARTCNTRL              0x0204
#define STARTCNTRL_START_MASK		BIT(0)

#define LINEINITCNT		0x0210
#define LPTXTIMECNT		0x0214
#define TCLK_HEADERCNT		0x0218
#define	TCLK_HEADERCNT_TCLK_ZEROCNT_MASK	GENMASK(15, 8)
#define TCLK_HEADERCNT_TCLK_PREPARECNT_MASK	GENMASK(6, 0)
#define	TCLK_HEADERCNT_TCLK_ZEROCNT_SET(val)	((val << 8) & TCLK_HEADERCNT_TCLK_ZEROCNT_MASK)
#define	TCLK_HEADERCNT_TCLK_PREPARECNT_SET(val)	(val & TCLK_HEADERCNT_TCLK_PREPARECNT_MASK)

#define TCLK_TRAILCNT		0x021C
#define THS_HEADERCNT		0x0220
#define	THS_HEADERCNT_THS_ZEROCNT_MASK		GENMASK(14, 8)
#define	THS_HEADERCNT_THS_PREPARECNT_MASK	GENMASK(6, 0)
#define	THS_HEADERCNT_THS_ZEROCNT_SET(val)	((val << 8) & THS_HEADERCNT_THS_ZEROCNT_MASK)
#define	THS_HEADERCNT_THS_PREPARECNT_SET(val)	(val & THS_HEADERCNT_THS_PREPARECNT_MASK)

#define TWAKEUP			0x0224
#define TCLK_POSTCNT		0x0228
#define THS_TRAILCNT		0x022C
#define HSTXVREGCNT		0x0230
#define HSTXVREGEN              0x0234
#define HSTXVREGEN_D3M_HSTXVREGEN_MASK	BIT(4)
#define HSTXVREGEN_D2M_HSTXVREGEN_MASK  BIT(3)
#define HSTXVREGEN_D1M_HSTXVREGEN_MASK  BIT(2)
#define HSTXVREGEN_D0M_HSTXVREGEN_MASK  BIT(1)
#define HSTXVREGEN_CLM_HSTXVREGEN_MASK  BIT(0)

#define TXOPTIONCNTRL           0x0238
#define TXOPTIONCNTRL_CONTCLKMODE_MASK	BIT(0)

#define CSI_CONTROL             0x040C
#define CSI_CONTROL_CSI_MODE_MASK       BIT(15)
#define CSI_CONTROL_HTXTOEN_MASK        BIT(10)
#define CSI_CONTROL_TXHSMD_MASK         BIT(7)
#define CSI_CONTROL_NOL_MASK            GENMASK(2, 1)
#define CSI_CONTROL_NOL_1_MASK          0
#define CSI_CONTROL_NOL_2_MASK          BIT(1)
#define CSI_CONTROL_NOL_3_MASK          BIT(2)
#define CSI_CONTROL_NOL_4_MASK          (BIT(1) | BIT(2))
#define CSI_CONTROL_EOTDIS_MASK         BIT(0)

#define CSI_STATUS              0x0410
#define CSI_STATUS_S_WSYNC_MASK		BIT(10)
#define CSI_STATUS_S_TXACT_MASK		BIT(9)
#define CSI_STATUS_S_HLT_MASK		BIT(0)

#define CSI_INT			0x0414
#define CSI_INT_INTHLT_MASK		BIT(3)
#define CSI_INT_INTER_MASK		BIT(2)

#define CSI_INT_ENA             0x0418
#define CSI_INT_ENA_IENHLT_MASK		BIT(3)
#define CSI_INT_ENA_IENER_MASK		BIT(2)

#define CSI_ERR                 0x044C
#define CSI_ERR_INER_MASK               BIT(9)
#define CSI_ERR_WCER_MASK		BIT(8)
#define CSI_ERR_QUNK_MASK		BIT(4)
#define CSI_ERR_TXBRK_MASK		BIT(1)

#define CSI_ERR_INTENA          0x0450
#define CSI_ERR_HALT            0x0454
#define CSI_CONFW               0x0500
#define CSI_CONFW_MODE_MASK			GENMASK(31, 29)
#define CSI_CONFW_MODE_SET_MASK			(BIT(31) | BIT(29))
#define CSI_CONFW_MODE_CLEAR_MASK		(BIT(31) | BIT(30))
#define CSI_CONFW_ADDRESS_MASK			GENMASK(28, 24)
#define CSI_CONFW_ADDRESS_CSI_CONTROL_MASK	(BIT(24) | BIT(25))
#define CSI_CONFW_ADDRESS_CSI_INT_ENA_MASK	(BIT(25) | BIT(26))
#define CSI_CONFW_ADDRESS_CSI_ERR_INTENA_MASK	(BIT(28) | BIT(26))
#define CSI_CONFW_ADDRESS_CSI_ERR_HALT_MASK	(BIT(28) | BIT(26) | BIT(24))
#define CSI_CONFW_DATA_MASK			GENMASK(15, 0)

#define CSIRESET                0x0504
#define CSIRESET_RESET_CNF_MASK		BIT(1)
#define CSIRESET_RESET_MODULE_MASK	BIT(0)

#define CSI_INT_CLR             0x050C
#define CSI_INT_CLR_ICRER_MASK		BIT(2)

#define CSI_START               0x0518
#define CSI_START_STRT_MASK		BIT(0)

#endif
